/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package demineur_cordier_elziere_dompietrini;

import java.awt.Image;
import java.util.Random;
import javax.swing.JLabel;

/**
 *
 * @author Nina
 */
public class PlateauDeJeu extends javax.swing.JPanel {

    /*initialisation des constantes*/
    private final int CELL_COUV = 10; /*état de la case initiale : couverte*/
    private final int CELL_MINE = 9; /*état de la case s'il y a une mine*/
    private final int CELL_MINE_COUV = CELL_MINE + CELL_COUV; /*si la cellule est minée et couverte*/


    private final int NB_MINES = 50; /*nombre de mines initialisé à 50*/
    private final int NB_LIG = 16; /*16 lignes*/
    private final int NB_COL = 30; /*30 colonnes*/


    /*ajout de propriétés*/
    private int[] tableau;
    private boolean fin_jeu; /*permettra de voir si le joueur a gagné ou non*/
    private int mines_restantes; /*nombre de mines non découvertes*/

    private int nb_cellules; /*nombre de cellules totales*/
    private final JLabel message;

    /**
     * Creates new form PlateauDeJeu
     */
    public PlateauDeJeu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
